# Generated by Django 3.2.9 on 2021-11-02 21:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BagProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image_1', models.ImageField(help_text='Bag product image', upload_to='bag_product')),
                ('image_2', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('image_3', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('image_4', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('image_5', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('women', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=True)),
                ('kind', models.CharField(default='bag, belt, jewelry', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tesis', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(help_text='Banner image', upload_to='banner/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='MenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image_1', models.ImageField(help_text='Men product image', upload_to='men_product')),
                ('image_2', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('image_3', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('image_4', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('image_5', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('new', models.BooleanField(default=True)),
                ('kind', models.CharField(default='jacket, pants, t-short, sweatshirt, dress, shoes', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WomenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image_1', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='women')),
                ('image_2', models.ImageField(blank=True, help_text='Women product image', upload_to='women_product')),
                ('image_3', models.ImageField(blank=True, help_text='Women product image', upload_to='women_product')),
                ('image_4', models.ImageField(blank=True, help_text='Women product image', upload_to='women_product')),
                ('image_5', models.ImageField(blank=True, help_text='Women product image', upload_to='women_product')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('new', models.BooleanField(default=True)),
                ('kind', models.CharField(default='jacket, pants, t-short, sweatshirt, dress, shoes', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
