# Generated by Django 3.2.9 on 2021-11-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendy', '0002_auto_20211102_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BagProduct',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='MenProduct',
        ),
        migrations.DeleteModel(
            name='WomenProduct',
        ),
    ]
