# Generated by Django 3.2.9 on 2021-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendy', '0009_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
